version: '2'
services:
  server:
    container_name: my-server
    restart: always
    build: .
    ports:
      - "3003:3003"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./src/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro