version: '1.0'
services:
  server:
    container_name: server
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - db
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    environment:
      MONGO_URI: mongodb://mongodb:27017/libraryDB
  db:
    container_name: db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./src/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro